[package]
name = "nyabase-sftp-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nyabase-sftp-server"
path = "src/main.rs"

[dependencies]
bytes = "1"
russh-sftp = "2.3"
tokio = { version = "1", features = ["io-std", "io-util", "macros", "rt-multi-thread"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
