import {
  MAX_MANAGED_CONTAINERS_PER_SERVER,
  MAX_PLATFORM_SERVERS,
} from '@nyabase/common';

export const MAX_NETWORK_ADDRESS_CLAIMS_GLOBAL = MAX_PLATFORM_SERVERS
  * (MAX_MANAGED_CONTAINERS_PER_SERVER + 1) * 2;

export const NETWORK_CLAIM_GC_BATCH = 4_096;
