/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as SystemSettingsIndexRouteImport } from './routes/system-settings/index'
import { Route as SshProxyIndexRouteImport } from './routes/ssh-proxy/index'
import { Route as ServersIndexRouteImport } from './routes/servers/index'
import { Route as ImagesIndexRouteImport } from './routes/images/index'
import { Route as HttpProxyIndexRouteImport } from './routes/http-proxy/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as DataDirsIndexRouteImport } from './routes/data-dirs/index'
import { Route as ContainersIndexRouteImport } from './routes/containers/index'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as ServersIdRouteImport } from './routes/servers/$id'
import { Route as GroupsIdRouteImport } from './routes/groups/$id'
import { Route as ContainersContainerIdRouteImport } from './routes/containers/$containerId'
import { Route as ManageRemoteFsIndexRouteImport } from './routes/manage/remote-fs/index'
import { Route as ManageContainersIndexRouteImport } from './routes/manage/containers/index'
import { Route as ManageContainersContainerIdRouteImport } from './routes/manage/containers/$containerId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSettingsIndexRoute = SystemSettingsIndexRouteImport.update({
  id: '/system-settings/',
  path: '/system-settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SshProxyIndexRoute = SshProxyIndexRouteImport.update({
  id: '/ssh-proxy/',
  path: '/ssh-proxy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIndexRoute = ServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesIndexRoute = ImagesIndexRouteImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpProxyIndexRoute = HttpProxyIndexRouteImport.update({
  id: '/http-proxy/',
  path: '/http-proxy/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDirsIndexRoute = DataDirsIndexRouteImport.update({
  id: '/data-dirs/',
  path: '/data-dirs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersIndexRoute = ContainersIndexRouteImport.update({
  id: '/containers/',
  path: '/containers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIdRoute = ServersIdRouteImport.update({
  id: '/servers/$id',
  path: '/servers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdRoute = GroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersContainerIdRoute = ContainersContainerIdRouteImport.update({
  id: '/containers/$containerId',
  path: '/containers/$containerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRemoteFsIndexRoute = ManageRemoteFsIndexRouteImport.update({
  id: '/manage/remote-fs/',
  path: '/manage/remote-fs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageContainersIndexRoute = ManageContainersIndexRouteImport.update({
  id: '/manage/containers/',
  path: '/manage/containers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageContainersContainerIdRoute =
  ManageContainersContainerIdRouteImport.update({
    id: '/manage/containers/$containerId',
    path: '/manage/containers/$containerId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/containers/$containerId': typeof ContainersContainerIdRoute
  '/groups/$id': typeof GroupsIdRoute
  '/servers/$id': typeof ServersIdRoute
  '/audit/': typeof AuditIndexRoute
  '/containers/': typeof ContainersIndexRoute
  '/data-dirs/': typeof DataDirsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/http-proxy/': typeof HttpProxyIndexRoute
  '/images/': typeof ImagesIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/ssh-proxy/': typeof SshProxyIndexRoute
  '/system-settings/': typeof SystemSettingsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/manage/containers/$containerId': typeof ManageContainersContainerIdRoute
  '/manage/containers/': typeof ManageContainersIndexRoute
  '/manage/remote-fs/': typeof ManageRemoteFsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/containers/$containerId': typeof ContainersContainerIdRoute
  '/groups/$id': typeof GroupsIdRoute
  '/servers/$id': typeof ServersIdRoute
  '/audit': typeof AuditIndexRoute
  '/containers': typeof ContainersIndexRoute
  '/data-dirs': typeof DataDirsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/http-proxy': typeof HttpProxyIndexRoute
  '/images': typeof ImagesIndexRoute
  '/servers': typeof ServersIndexRoute
  '/ssh-proxy': typeof SshProxyIndexRoute
  '/system-settings': typeof SystemSettingsIndexRoute
  '/users': typeof UsersIndexRoute
  '/manage/containers/$containerId': typeof ManageContainersContainerIdRoute
  '/manage/containers': typeof ManageContainersIndexRoute
  '/manage/remote-fs': typeof ManageRemoteFsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/containers/$containerId': typeof ContainersContainerIdRoute
  '/groups/$id': typeof GroupsIdRoute
  '/servers/$id': typeof ServersIdRoute
  '/audit/': typeof AuditIndexRoute
  '/containers/': typeof ContainersIndexRoute
  '/data-dirs/': typeof DataDirsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/http-proxy/': typeof HttpProxyIndexRoute
  '/images/': typeof ImagesIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/ssh-proxy/': typeof SshProxyIndexRoute
  '/system-settings/': typeof SystemSettingsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/manage/containers/$containerId': typeof ManageContainersContainerIdRoute
  '/manage/containers/': typeof ManageContainersIndexRoute
  '/manage/remote-fs/': typeof ManageRemoteFsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/containers/$containerId'
    | '/groups/$id'
    | '/servers/$id'
    | '/audit/'
    | '/containers/'
    | '/data-dirs/'
    | '/groups/'
    | '/http-proxy/'
    | '/images/'
    | '/servers/'
    | '/ssh-proxy/'
    | '/system-settings/'
    | '/users/'
    | '/manage/containers/$containerId'
    | '/manage/containers/'
    | '/manage/remote-fs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/containers/$containerId'
    | '/groups/$id'
    | '/servers/$id'
    | '/audit'
    | '/containers'
    | '/data-dirs'
    | '/groups'
    | '/http-proxy'
    | '/images'
    | '/servers'
    | '/ssh-proxy'
    | '/system-settings'
    | '/users'
    | '/manage/containers/$containerId'
    | '/manage/containers'
    | '/manage/remote-fs'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/containers/$containerId'
    | '/groups/$id'
    | '/servers/$id'
    | '/audit/'
    | '/containers/'
    | '/data-dirs/'
    | '/groups/'
    | '/http-proxy/'
    | '/images/'
    | '/servers/'
    | '/ssh-proxy/'
    | '/system-settings/'
    | '/users/'
    | '/manage/containers/$containerId'
    | '/manage/containers/'
    | '/manage/remote-fs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ContainersContainerIdRoute: typeof ContainersContainerIdRoute
  GroupsIdRoute: typeof GroupsIdRoute
  ServersIdRoute: typeof ServersIdRoute
  AuditIndexRoute: typeof AuditIndexRoute
  ContainersIndexRoute: typeof ContainersIndexRoute
  DataDirsIndexRoute: typeof DataDirsIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  HttpProxyIndexRoute: typeof HttpProxyIndexRoute
  ImagesIndexRoute: typeof ImagesIndexRoute
  ServersIndexRoute: typeof ServersIndexRoute
  SshProxyIndexRoute: typeof SshProxyIndexRoute
  SystemSettingsIndexRoute: typeof SystemSettingsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ManageContainersContainerIdRoute: typeof ManageContainersContainerIdRoute
  ManageContainersIndexRoute: typeof ManageContainersIndexRoute
  ManageRemoteFsIndexRoute: typeof ManageRemoteFsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-settings/': {
      id: '/system-settings/'
      path: '/system-settings'
      fullPath: '/system-settings/'
      preLoaderRoute: typeof SystemSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssh-proxy/': {
      id: '/ssh-proxy/'
      path: '/ssh-proxy'
      fullPath: '/ssh-proxy/'
      preLoaderRoute: typeof SshProxyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/': {
      id: '/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof ServersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/': {
      id: '/images/'
      path: '/images'
      fullPath: '/images/'
      preLoaderRoute: typeof ImagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/http-proxy/': {
      id: '/http-proxy/'
      path: '/http-proxy'
      fullPath: '/http-proxy/'
      preLoaderRoute: typeof HttpProxyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-dirs/': {
      id: '/data-dirs/'
      path: '/data-dirs'
      fullPath: '/data-dirs/'
      preLoaderRoute: typeof DataDirsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/': {
      id: '/containers/'
      path: '/containers'
      fullPath: '/containers/'
      preLoaderRoute: typeof ContainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$id': {
      id: '/servers/$id'
      path: '/servers/$id'
      fullPath: '/servers/$id'
      preLoaderRoute: typeof ServersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id': {
      id: '/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof GroupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/$containerId': {
      id: '/containers/$containerId'
      path: '/containers/$containerId'
      fullPath: '/containers/$containerId'
      preLoaderRoute: typeof ContainersContainerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/remote-fs/': {
      id: '/manage/remote-fs/'
      path: '/manage/remote-fs'
      fullPath: '/manage/remote-fs/'
      preLoaderRoute: typeof ManageRemoteFsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/containers/': {
      id: '/manage/containers/'
      path: '/manage/containers'
      fullPath: '/manage/containers/'
      preLoaderRoute: typeof ManageContainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/containers/$containerId': {
      id: '/manage/containers/$containerId'
      path: '/manage/containers/$containerId'
      fullPath: '/manage/containers/$containerId'
      preLoaderRoute: typeof ManageContainersContainerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ContainersContainerIdRoute: ContainersContainerIdRoute,
  GroupsIdRoute: GroupsIdRoute,
  ServersIdRoute: ServersIdRoute,
  AuditIndexRoute: AuditIndexRoute,
  ContainersIndexRoute: ContainersIndexRoute,
  DataDirsIndexRoute: DataDirsIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  HttpProxyIndexRoute: HttpProxyIndexRoute,
  ImagesIndexRoute: ImagesIndexRoute,
  ServersIndexRoute: ServersIndexRoute,
  SshProxyIndexRoute: SshProxyIndexRoute,
  SystemSettingsIndexRoute: SystemSettingsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ManageContainersContainerIdRoute: ManageContainersContainerIdRoute,
  ManageContainersIndexRoute: ManageContainersIndexRoute,
  ManageRemoteFsIndexRoute: ManageRemoteFsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
