/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VolumesIndexRouteImport } from './routes/volumes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as SystemSettingsIndexRouteImport } from './routes/system-settings/index'
import { Route as StoragePoolsIndexRouteImport } from './routes/storage-pools/index'
import { Route as SshProxyIndexRouteImport } from './routes/ssh-proxy/index'
import { Route as SharedVolumesIndexRouteImport } from './routes/shared-volumes/index'
import { Route as SharedBackendsIndexRouteImport } from './routes/shared-backends/index'
import { Route as ServersIndexRouteImport } from './routes/servers/index'
import { Route as IpPoolsIndexRouteImport } from './routes/ip-pools/index'
import { Route as ImagesIndexRouteImport } from './routes/images/index'
import { Route as HttpProxyIndexRouteImport } from './routes/http-proxy/index'
import { Route as HttpProxyOpsIndexRouteImport } from './routes/http-proxy-ops/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as ContainersIndexRouteImport } from './routes/containers/index'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as ServersIdRouteImport } from './routes/servers/$id'
import { Route as GroupsIdRouteImport } from './routes/groups/$id'
import { Route as ContainersContainerIdRouteImport } from './routes/containers/$containerId'
import { Route as ManageSharedVolumesIndexRouteImport } from './routes/manage/shared-volumes/index'
import { Route as ManageVolumesIndexRouteImport } from './routes/manage/volumes/index'
import { Route as ManageContainersIndexRouteImport } from './routes/manage/containers/index'
import { Route as ManageContainersContainerIdRouteImport } from './routes/manage/containers/$containerId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumesIndexRoute = VolumesIndexRouteImport.update({
  id: '/volumes/',
  path: '/volumes/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSettingsIndexRoute = SystemSettingsIndexRouteImport.update({
  id: '/system-settings/',
  path: '/system-settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoragePoolsIndexRoute = StoragePoolsIndexRouteImport.update({
  id: '/storage-pools/',
  path: '/storage-pools/',
  getParentRoute: () => rootRouteImport,
} as any)
const SshProxyIndexRoute = SshProxyIndexRouteImport.update({
  id: '/ssh-proxy/',
  path: '/ssh-proxy/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedVolumesIndexRoute = SharedVolumesIndexRouteImport.update({
  id: '/shared-volumes/',
  path: '/shared-volumes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedBackendsIndexRoute = SharedBackendsIndexRouteImport.update({
  id: '/shared-backends/',
  path: '/shared-backends/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIndexRoute = ServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => rootRouteImport,
} as any)
const IpPoolsIndexRoute = IpPoolsIndexRouteImport.update({
  id: '/ip-pools/',
  path: '/ip-pools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesIndexRoute = ImagesIndexRouteImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpProxyIndexRoute = HttpProxyIndexRouteImport.update({
  id: '/http-proxy/',
  path: '/http-proxy/',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpProxyOpsIndexRoute = HttpProxyOpsIndexRouteImport.update({
  id: '/http-proxy-ops/',
  path: '/http-proxy-ops/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersIndexRoute = ContainersIndexRouteImport.update({
  id: '/containers/',
  path: '/containers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIdRoute = ServersIdRouteImport.update({
  id: '/servers/$id',
  path: '/servers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdRoute = GroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersContainerIdRoute = ContainersContainerIdRouteImport.update({
  id: '/containers/$containerId',
  path: '/containers/$containerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSharedVolumesIndexRoute =
  ManageSharedVolumesIndexRouteImport.update({
    id: '/manage/shared-volumes/',
    path: '/manage/shared-volumes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManageVolumesIndexRoute = ManageVolumesIndexRouteImport.update({
  id: '/manage/volumes/',
  path: '/manage/volumes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageContainersIndexRoute = ManageContainersIndexRouteImport.update({
  id: '/manage/containers/',
  path: '/manage/containers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageContainersContainerIdRoute =
  ManageContainersContainerIdRouteImport.update({
    id: '/manage/containers/$containerId',
    path: '/manage/containers/$containerId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/containers/$containerId': typeof ContainersContainerIdRoute
  '/groups/$id': typeof GroupsIdRoute
  '/servers/$id': typeof ServersIdRoute
  '/audit/': typeof AuditIndexRoute
  '/containers/': typeof ContainersIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/http-proxy-ops/': typeof HttpProxyOpsIndexRoute
  '/http-proxy/': typeof HttpProxyIndexRoute
  '/images/': typeof ImagesIndexRoute
  '/ip-pools/': typeof IpPoolsIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/shared-backends/': typeof SharedBackendsIndexRoute
  '/shared-volumes/': typeof SharedVolumesIndexRoute
  '/ssh-proxy/': typeof SshProxyIndexRoute
  '/storage-pools/': typeof StoragePoolsIndexRoute
  '/system-settings/': typeof SystemSettingsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/volumes/': typeof VolumesIndexRoute
  '/manage/containers/$containerId': typeof ManageContainersContainerIdRoute
  '/manage/containers/': typeof ManageContainersIndexRoute
  '/manage/shared-volumes/': typeof ManageSharedVolumesIndexRoute
  '/manage/volumes/': typeof ManageVolumesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/containers/$containerId': typeof ContainersContainerIdRoute
  '/groups/$id': typeof GroupsIdRoute
  '/servers/$id': typeof ServersIdRoute
  '/audit': typeof AuditIndexRoute
  '/containers': typeof ContainersIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/http-proxy-ops': typeof HttpProxyOpsIndexRoute
  '/http-proxy': typeof HttpProxyIndexRoute
  '/images': typeof ImagesIndexRoute
  '/ip-pools': typeof IpPoolsIndexRoute
  '/servers': typeof ServersIndexRoute
  '/shared-backends': typeof SharedBackendsIndexRoute
  '/shared-volumes': typeof SharedVolumesIndexRoute
  '/ssh-proxy': typeof SshProxyIndexRoute
  '/storage-pools': typeof StoragePoolsIndexRoute
  '/system-settings': typeof SystemSettingsIndexRoute
  '/users': typeof UsersIndexRoute
  '/volumes': typeof VolumesIndexRoute
  '/manage/containers/$containerId': typeof ManageContainersContainerIdRoute
  '/manage/containers': typeof ManageContainersIndexRoute
  '/manage/shared-volumes': typeof ManageSharedVolumesIndexRoute
  '/manage/volumes': typeof ManageVolumesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/containers/$containerId': typeof ContainersContainerIdRoute
  '/groups/$id': typeof GroupsIdRoute
  '/servers/$id': typeof ServersIdRoute
  '/audit/': typeof AuditIndexRoute
  '/containers/': typeof ContainersIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/http-proxy-ops/': typeof HttpProxyOpsIndexRoute
  '/http-proxy/': typeof HttpProxyIndexRoute
  '/images/': typeof ImagesIndexRoute
  '/ip-pools/': typeof IpPoolsIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/shared-backends/': typeof SharedBackendsIndexRoute
  '/shared-volumes/': typeof SharedVolumesIndexRoute
  '/ssh-proxy/': typeof SshProxyIndexRoute
  '/storage-pools/': typeof StoragePoolsIndexRoute
  '/system-settings/': typeof SystemSettingsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/volumes/': typeof VolumesIndexRoute
  '/manage/containers/$containerId': typeof ManageContainersContainerIdRoute
  '/manage/containers/': typeof ManageContainersIndexRoute
  '/manage/shared-volumes/': typeof ManageSharedVolumesIndexRoute
  '/manage/volumes/': typeof ManageVolumesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/containers/$containerId'
    | '/groups/$id'
    | '/servers/$id'
    | '/audit/'
    | '/containers/'
    | '/groups/'
    | '/http-proxy-ops/'
    | '/http-proxy/'
    | '/images/'
    | '/ip-pools/'
    | '/servers/'
    | '/shared-backends/'
    | '/shared-volumes/'
    | '/ssh-proxy/'
    | '/storage-pools/'
    | '/system-settings/'
    | '/users/'
    | '/volumes/'
    | '/manage/containers/$containerId'
    | '/manage/containers/'
    | '/manage/shared-volumes/'
    | '/manage/volumes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/containers/$containerId'
    | '/groups/$id'
    | '/servers/$id'
    | '/audit'
    | '/containers'
    | '/groups'
    | '/http-proxy-ops'
    | '/http-proxy'
    | '/images'
    | '/ip-pools'
    | '/servers'
    | '/shared-backends'
    | '/shared-volumes'
    | '/ssh-proxy'
    | '/storage-pools'
    | '/system-settings'
    | '/users'
    | '/volumes'
    | '/manage/containers/$containerId'
    | '/manage/containers'
    | '/manage/shared-volumes'
    | '/manage/volumes'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/containers/$containerId'
    | '/groups/$id'
    | '/servers/$id'
    | '/audit/'
    | '/containers/'
    | '/groups/'
    | '/http-proxy-ops/'
    | '/http-proxy/'
    | '/images/'
    | '/ip-pools/'
    | '/servers/'
    | '/shared-backends/'
    | '/shared-volumes/'
    | '/ssh-proxy/'
    | '/storage-pools/'
    | '/system-settings/'
    | '/users/'
    | '/volumes/'
    | '/manage/containers/$containerId'
    | '/manage/containers/'
    | '/manage/shared-volumes/'
    | '/manage/volumes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ContainersContainerIdRoute: typeof ContainersContainerIdRoute
  GroupsIdRoute: typeof GroupsIdRoute
  ServersIdRoute: typeof ServersIdRoute
  AuditIndexRoute: typeof AuditIndexRoute
  ContainersIndexRoute: typeof ContainersIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  HttpProxyOpsIndexRoute: typeof HttpProxyOpsIndexRoute
  HttpProxyIndexRoute: typeof HttpProxyIndexRoute
  ImagesIndexRoute: typeof ImagesIndexRoute
  IpPoolsIndexRoute: typeof IpPoolsIndexRoute
  ServersIndexRoute: typeof ServersIndexRoute
  SharedBackendsIndexRoute: typeof SharedBackendsIndexRoute
  SharedVolumesIndexRoute: typeof SharedVolumesIndexRoute
  SshProxyIndexRoute: typeof SshProxyIndexRoute
  StoragePoolsIndexRoute: typeof StoragePoolsIndexRoute
  SystemSettingsIndexRoute: typeof SystemSettingsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  VolumesIndexRoute: typeof VolumesIndexRoute
  ManageContainersContainerIdRoute: typeof ManageContainersContainerIdRoute
  ManageContainersIndexRoute: typeof ManageContainersIndexRoute
  ManageSharedVolumesIndexRoute: typeof ManageSharedVolumesIndexRoute
  ManageVolumesIndexRoute: typeof ManageVolumesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volumes/': {
      id: '/volumes/'
      path: '/volumes'
      fullPath: '/volumes/'
      preLoaderRoute: typeof VolumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-settings/': {
      id: '/system-settings/'
      path: '/system-settings'
      fullPath: '/system-settings/'
      preLoaderRoute: typeof SystemSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage-pools/': {
      id: '/storage-pools/'
      path: '/storage-pools'
      fullPath: '/storage-pools/'
      preLoaderRoute: typeof StoragePoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssh-proxy/': {
      id: '/ssh-proxy/'
      path: '/ssh-proxy'
      fullPath: '/ssh-proxy/'
      preLoaderRoute: typeof SshProxyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-volumes/': {
      id: '/shared-volumes/'
      path: '/shared-volumes'
      fullPath: '/shared-volumes/'
      preLoaderRoute: typeof SharedVolumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-backends/': {
      id: '/shared-backends/'
      path: '/shared-backends'
      fullPath: '/shared-backends/'
      preLoaderRoute: typeof SharedBackendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/': {
      id: '/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof ServersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip-pools/': {
      id: '/ip-pools/'
      path: '/ip-pools'
      fullPath: '/ip-pools/'
      preLoaderRoute: typeof IpPoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/': {
      id: '/images/'
      path: '/images'
      fullPath: '/images/'
      preLoaderRoute: typeof ImagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/http-proxy/': {
      id: '/http-proxy/'
      path: '/http-proxy'
      fullPath: '/http-proxy/'
      preLoaderRoute: typeof HttpProxyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/http-proxy-ops/': {
      id: '/http-proxy-ops/'
      path: '/http-proxy-ops'
      fullPath: '/http-proxy-ops/'
      preLoaderRoute: typeof HttpProxyOpsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/': {
      id: '/containers/'
      path: '/containers'
      fullPath: '/containers/'
      preLoaderRoute: typeof ContainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$id': {
      id: '/servers/$id'
      path: '/servers/$id'
      fullPath: '/servers/$id'
      preLoaderRoute: typeof ServersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id': {
      id: '/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof GroupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/$containerId': {
      id: '/containers/$containerId'
      path: '/containers/$containerId'
      fullPath: '/containers/$containerId'
      preLoaderRoute: typeof ContainersContainerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/shared-volumes/': {
      id: '/manage/shared-volumes/'
      path: '/manage/shared-volumes'
      fullPath: '/manage/shared-volumes/'
      preLoaderRoute: typeof ManageSharedVolumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/volumes/': {
      id: '/manage/volumes/'
      path: '/manage/volumes'
      fullPath: '/manage/volumes/'
      preLoaderRoute: typeof ManageVolumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/containers/': {
      id: '/manage/containers/'
      path: '/manage/containers'
      fullPath: '/manage/containers/'
      preLoaderRoute: typeof ManageContainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/containers/$containerId': {
      id: '/manage/containers/$containerId'
      path: '/manage/containers/$containerId'
      fullPath: '/manage/containers/$containerId'
      preLoaderRoute: typeof ManageContainersContainerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ContainersContainerIdRoute: ContainersContainerIdRoute,
  GroupsIdRoute: GroupsIdRoute,
  ServersIdRoute: ServersIdRoute,
  AuditIndexRoute: AuditIndexRoute,
  ContainersIndexRoute: ContainersIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  HttpProxyOpsIndexRoute: HttpProxyOpsIndexRoute,
  HttpProxyIndexRoute: HttpProxyIndexRoute,
  ImagesIndexRoute: ImagesIndexRoute,
  IpPoolsIndexRoute: IpPoolsIndexRoute,
  ServersIndexRoute: ServersIndexRoute,
  SharedBackendsIndexRoute: SharedBackendsIndexRoute,
  SharedVolumesIndexRoute: SharedVolumesIndexRoute,
  SshProxyIndexRoute: SshProxyIndexRoute,
  StoragePoolsIndexRoute: StoragePoolsIndexRoute,
  SystemSettingsIndexRoute: SystemSettingsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  VolumesIndexRoute: VolumesIndexRoute,
  ManageContainersContainerIdRoute: ManageContainersContainerIdRoute,
  ManageContainersIndexRoute: ManageContainersIndexRoute,
  ManageSharedVolumesIndexRoute: ManageSharedVolumesIndexRoute,
  ManageVolumesIndexRoute: ManageVolumesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
