import { AuditAction } from '@nyabase/common';

export const AUDIT_RESOURCE_LABELS: Record<string, string> = {
  user: '用户',
  group: '用户组',
  server: '服务器',
  image: '镜像',
  image_assignment: '镜像分配',
  container: '容器',
  volume: '数据卷',
  storage_pool: '存储池',
  shared_backend: '共享存储',
  ip_pool: 'IP 池',
  http_proxy_binding: 'HTTP 发布',
  http_domain_pool: 'HTTP 域名池',
  intent: '意图',
  grant: '授权',
  certificate: '证书',
  system_settings: '系统设置',
  ssh_proxy: 'SSH 代理',
  api_token: 'API 令牌',
  ssh_public_key: 'SSH 公钥',
};

const AUDIT_ACTION_LABELS: Record<string, string> = {
  [AuditAction.CreateContainer]: '创建容器',
  [AuditAction.StartContainer]: '启动容器',
  [AuditAction.StopContainer]: '停止容器',
  [AuditAction.RestartContainer]: '重启容器',
  [AuditAction.DeleteContainer]: '删除容器',
  [AuditAction.UpdateContainerLimits]: '更新容器限额',
  [AuditAction.ResizeContainerRoot]: '调整系统盘',
  [AuditAction.UpdateContainerGpu]: '更新容器 GPU',
  [AuditAction.AttachVolume]: '挂载数据卷',
  [AuditAction.DetachVolume]: '卸载数据卷',
  [AuditAction.CreateExecSession]: '创建终端会话',
  [AuditAction.CreateServer]: '登记服务器',
  [AuditAction.UpdateServer]: '更新服务器',
  [AuditAction.DeleteServer]: '删除服务器',
  [AuditAction.ConnectServer]: '连接服务器',
  [AuditAction.RunServerPreflight]: '运行前置检查',
  [AuditAction.RegisterStoragePool]: '登记存储池',
  [AuditAction.CreateIpPool]: '创建 IP 池',
  [AuditAction.UpdateIpPool]: '更新 IP 池',
  [AuditAction.DeleteIpPool]: '删除 IP 池',
  [AuditAction.CreateSharedBackend]: '登记共享存储',
  [AuditAction.UpdateSharedBackend]: '更新共享存储',
  [AuditAction.DeleteSharedBackend]: '删除共享存储',
  [AuditAction.CreateVolume]: '创建数据卷',
  [AuditAction.UpdateVolume]: '更新数据卷',
  [AuditAction.DeleteVolume]: '删除数据卷',
  [AuditAction.EnsureVolume]: '确保数据卷',
  [AuditAction.ResizeVolume]: '调整数据卷容量',
  [AuditAction.CreateImage]: '创建镜像',
  [AuditAction.UpdateImage]: '更新镜像',
  [AuditAction.DeleteImage]: '删除镜像',
  [AuditAction.EnsureImageAssignment]: '分配镜像',
  [AuditAction.DeleteImageAssignment]: '取消镜像分配',
  [AuditAction.UpsertServerGrant]: '更新服务器授权',
  [AuditAction.DeleteServerGrant]: '删除服务器授权',
  [AuditAction.UpsertStoragePoolGrant]: '更新存储池授权',
  [AuditAction.DeleteStoragePoolGrant]: '删除存储池授权',
  [AuditAction.UpsertSharedBackendGrant]: '更新共享存储授权',
  [AuditAction.DeleteSharedBackendGrant]: '删除共享存储授权',
  [AuditAction.GrantExpired]: '授权到期',
  [AuditAction.ExpiryStopContainers]: '到期停止容器',
  [AuditAction.ExpiryPurgeResources]: '到期清理资源',
  [AuditAction.RotateIncusClientCertificate]: '轮换客户端证书',
  [AuditAction.UpdateSystemSettings]: '更新系统设置',
  [AuditAction.CreateUser]: '创建用户',
  [AuditAction.UpdateUser]: '更新用户',
  [AuditAction.DeleteUser]: '删除用户',
  [AuditAction.AddUserSshPublicKey]: '添加 SSH 公钥',
  [AuditAction.DeleteUserSshPublicKey]: '删除 SSH 公钥',
  [AuditAction.CreateGroup]: '创建用户组',
  [AuditAction.UpdateGroup]: '更新用户组',
  [AuditAction.DeleteGroup]: '删除用户组',
  [AuditAction.AddGroupMember]: '添加组成员',
  [AuditAction.RemoveGroupMember]: '移除组成员',
  [AuditAction.UserLogin]: '用户登录',
  [AuditAction.UserLogout]: '用户登出',
  [AuditAction.CreateApiToken]: '创建 API 令牌',
  [AuditAction.DeleteApiToken]: '删除 API 令牌',
  [AuditAction.CreateHttpProxyBinding]: '创建 HTTP 发布',
  [AuditAction.UpdateHttpProxyBinding]: '更新 HTTP 发布',
  [AuditAction.DeleteHttpProxyBinding]: '删除 HTTP 发布',
  [AuditAction.CreateHttpDomainPool]: '创建 HTTP 域名池',
  [AuditAction.UpdateHttpDomainPool]: '更新 HTTP 域名池',
  [AuditAction.DeleteHttpDomainPool]: '删除 HTTP 域名池',
  [AuditAction.DisconnectSshProxySessions]: '断开 SSH 代理会话',
  [AuditAction.RotateSshProxyHostKey]: '轮换 SSH 主机密钥',
};

export function auditActionLabel(action: string): string {
  return AUDIT_ACTION_LABELS[action] ?? action;
}

export function auditResourceTypeLabel(type: string | null | undefined): string {
  if (!type) return '资源';
  return AUDIT_RESOURCE_LABELS[type] ?? type;
}
