import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1700000000000 implements MigrationInterface {
    name = 'InitialSchema1700000000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" text PRIMARY KEY NOT NULL, "numericId" integer, "username" text NOT NULL, "passwordHash" text NOT NULL, "displayName" text NOT NULL, "status" text NOT NULL DEFAULT ('active'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_b49087eba389191a7a1a5c16a88" UNIQUE ("numericId"), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" text PRIMARY KEY NOT NULL, "userId" text NOT NULL, "hash" text NOT NULL, "expiresAt" datetime NOT NULL, "revoked" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL, CONSTRAINT "UQ_2cf4b2a681a38f8044d688b9ccb" UNIQUE ("hash"))`);
        await queryRunner.query(`CREATE INDEX "IDX_610102b60fea1455310ccd299d" ON "refresh_tokens" ("userId") `);
        await queryRunner.query(`CREATE TABLE "api_tokens" ("id" text PRIMARY KEY NOT NULL, "userId" text NOT NULL, "name" text NOT NULL, "hash" text NOT NULL, "lastUsedAt" datetime, "createdAt" datetime NOT NULL, CONSTRAINT "UQ_1bf385c40e1d7ff26da4401c7fc" UNIQUE ("hash"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2a2ce819bd75cc0193bfb2692b" ON "api_tokens" ("userId") `);
        await queryRunner.query(`CREATE TABLE "ssh_public_keys" ("id" text PRIMARY KEY NOT NULL, "userId" text NOT NULL, "name" text NOT NULL, "keyText" text NOT NULL, "createdAt" datetime NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_e0ddc8263f98e68528814ac369" ON "ssh_public_keys" ("userId") `);
        await queryRunner.query(`CREATE TABLE "user_internal_ssh_keys" ("user_id" text PRIMARY KEY NOT NULL, "encrypted_private_key" text NOT NULL, "public_key" text NOT NULL, "fingerprint" text NOT NULL, "generation" integer NOT NULL DEFAULT (1), "rotated_at" datetime NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_39773aacbb3afac30ff3d62c4b" ON "user_internal_ssh_keys" ("fingerprint") `);
        await queryRunner.query(`CREATE TABLE "ssh_proxy_host_keys" ("id" text PRIMARY KEY NOT NULL, "encrypted_private_key" text NOT NULL, "public_key" text NOT NULL, "fingerprint" text NOT NULL, "generation" integer NOT NULL DEFAULT (1), "rotated_at" datetime NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "servers" ("id" text PRIMARY KEY NOT NULL, "name" text NOT NULL, "slug" text NOT NULL, "agentTokenHash" text NOT NULL, "hostFingerprint" text, "agentConfigFingerprint" text, "status" text NOT NULL DEFAULT ('unknown'), "quarantine_code" text, "quarantine_message" text, "lastSeenAt" datetime, "macvlan_cidr" text, "macvlan_gateway" text, "macvlan_reserved_ips" text NOT NULL DEFAULT ('[]'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5c148a3e0a635fa398f28a1cc2" ON "servers" ("slug") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3f639177f557bf7d508db5fa63" ON "servers" ("agentTokenHash") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_servers_host_fingerprint" ON "servers" ("hostFingerprint") `);
        await queryRunner.query(`CREATE INDEX "IDX_servers_quarantine_code" ON "servers" ("quarantine_code") `);
        await queryRunner.query(`CREATE TABLE "images" ("id" text PRIMARY KEY NOT NULL, "name" text NOT NULL, "dockerImage" text NOT NULL, "runtime_overrides" text NOT NULL DEFAULT ('{"uid":0,"entrypoint":null,"cmd":null,"init":false}'), "description" text, "isActive" boolean NOT NULL DEFAULT (1), "disable_ssh" boolean NOT NULL DEFAULT (0), "deleting" boolean NOT NULL DEFAULT (0), "cleanup_generation" integer NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_d46ee7424fcbbc896a457784f1e" UNIQUE ("name"), CONSTRAINT "UQ_images_docker_image" UNIQUE ("dockerImage"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" text PRIMARY KEY NOT NULL, "actorId" text, "actorName" text, "actorUsername" text, "actorSnapshot" text, "action" text NOT NULL, "targetId" text, "targetType" text, "targetName" text, "targetSnapshot" text, "related" text, "payload" text, "ts" datetime NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_2dc33f7f3c22e2e7badafca1d1" ON "audit_logs" ("actorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee229609cb2b7c62a2fc3a974" ON "audit_logs" ("ts") `);
        await queryRunner.query(`CREATE TABLE "groups" ("id" text PRIMARY KEY NOT NULL, "name" text NOT NULL, "description" text, "priority" integer NOT NULL DEFAULT (0), "isSystem" boolean NOT NULL DEFAULT (0), "capabilitiesJson" text NOT NULL DEFAULT ('[]'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_664ea405ae2a10c264d582ee563" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "group_members" ("id" text PRIMARY KEY NOT NULL, "groupId" text NOT NULL, "userId" text NOT NULL, CONSTRAINT "UQ_53f644f66a416c1542b743c0295" UNIQUE ("groupId", "userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1aa8d31831c3126947e7a713c2" ON "group_members" ("groupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fdef099303bcf0ffd9a4a7b18f" ON "group_members" ("userId") `);
        await queryRunner.query(`CREATE TABLE "server_grants" ("id" text PRIMARY KEY NOT NULL, "scope" text NOT NULL, "scopeId" text NOT NULL, "serverId" text NOT NULL, "cpuMillis" integer, "memBytes" text, "diskBytes" text, "gpuMode" text, "gpuIndices" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_1c0bf93a5c5a6896c7ececf22ea" UNIQUE ("scope", "scopeId", "serverId"), CONSTRAINT "FK_server_grants_server" FOREIGN KEY ("serverId") REFERENCES "servers" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE INDEX "IDX_4bbc526cc1fc7905565eb41ca3" ON "server_grants" ("scope") `);
        await queryRunner.query(`CREATE INDEX "IDX_07fac52f8b667d912da6065f64" ON "server_grants" ("scopeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_87ac83586ca63f150559d7809a" ON "server_grants" ("serverId") `);
        await queryRunner.query(`CREATE TABLE "image_grants" ("id" text PRIMARY KEY NOT NULL, "scope" text NOT NULL, "scopeId" text NOT NULL, "imageId" text NOT NULL, "serverId" text NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_c9483774b5ea8a5e26494e231f2" UNIQUE ("scope", "scopeId", "imageId", "serverId"), CONSTRAINT "FK_image_grants_image" FOREIGN KEY ("imageId") REFERENCES "images" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION, CONSTRAINT "FK_image_grants_server" FOREIGN KEY ("serverId") REFERENCES "servers" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE INDEX "IDX_b8191e1eefdba566bcbc1dc88f" ON "image_grants" ("scope") `);
        await queryRunner.query(`CREATE INDEX "IDX_b620a683f3df3f8b2a5eaf13af" ON "image_grants" ("scopeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d401dd45fe95076e33a4c8b796" ON "image_grants" ("imageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1060e7b773af9bb188a604f9b1" ON "image_grants" ("serverId") `);
        await queryRunner.query(`CREATE TABLE "remote_fs_mounts" ("id" text PRIMARY KEY NOT NULL, "name" text NOT NULL, "displayName" text, "description" text, "type" text NOT NULL, "hostMountPoint" text NOT NULL, "options" text NOT NULL DEFAULT (''), "params" text NOT NULL, "desiredState" text NOT NULL DEFAULT ('active'), "generation" integer NOT NULL DEFAULT (1), "lastTaskId" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_remote_fs_mount_host_path" ON "remote_fs_mounts" ("hostMountPoint") `);
        await queryRunner.query(`CREATE INDEX "IDX_e419b091a9c1a5aa47aad3e372" ON "remote_fs_mounts" ("desiredState") `);
        await queryRunner.query(`CREATE TABLE "mount_source_grants" ("id" text PRIMARY KEY NOT NULL, "scope" text NOT NULL, "scopeId" text NOT NULL, "sourceKind" text NOT NULL, "sourceId" text NOT NULL, "serverId" text, "sourceIdentity" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "CHK_mount_source_grants_shape" CHECK (("sourceKind" = 'local' AND "serverId" IS NOT NULL AND "sourceIdentity" IS NOT NULL AND length(trim("sourceIdentity")) > 0) OR ("sourceKind" = 'remote' AND "serverId" IS NULL AND "sourceIdentity" IS NULL)), CONSTRAINT "CHK_mount_source_grants_scope" CHECK ("scope" IN ('user', 'group')), CONSTRAINT "FK_mount_source_grants_server" FOREIGN KEY ("serverId") REFERENCES "servers" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE INDEX "IDX_4c8b9d866b47f9b769192471b4" ON "mount_source_grants" ("scope") `);
        await queryRunner.query(`CREATE INDEX "IDX_2c825d1696c548aae334d5e1b5" ON "mount_source_grants" ("scopeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c780d804567b09ff28869b5cc" ON "mount_source_grants" ("sourceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_mount_source_grants_server" ON "mount_source_grants" ("serverId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_mount_source_grants_remote" ON "mount_source_grants" ("scope", "scopeId", "sourceKind", "sourceId") WHERE "sourceKind" = 'remote'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_mount_source_grants_local" ON "mount_source_grants" ("scope", "scopeId", "sourceKind", "sourceId", "serverId", "sourceIdentity") WHERE "sourceKind" = 'local'`);
        await queryRunner.query(`CREATE TABLE "remote_fs_server_assignments" ("id" text PRIMARY KEY NOT NULL, "remoteFsMountId" text NOT NULL, "serverId" text NOT NULL, "desiredState" text NOT NULL DEFAULT ('ensuring'), "generation" integer NOT NULL DEFAULT (1), "lastTaskId" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_e9c7a8e6de5fbc457e6f6d5f540" UNIQUE ("remoteFsMountId", "serverId"), CONSTRAINT "FK_remote_fs_assignment_mount" FOREIGN KEY ("remoteFsMountId") REFERENCES "remote_fs_mounts" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION, CONSTRAINT "FK_remote_fs_assignment_server" FOREIGN KEY ("serverId") REFERENCES "servers" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE INDEX "IDX_a7881dfbbf08a86770d6452c83" ON "remote_fs_server_assignments" ("remoteFsMountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0fadae89939ccf83ae0d4bc69d" ON "remote_fs_server_assignments" ("serverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_102ce17e2ec3bf21db37f9338a" ON "remote_fs_server_assignments" ("desiredState") `);
        await queryRunner.query(`CREATE TABLE "data_directories" ("id" text PRIMARY KEY NOT NULL, "userId" text NOT NULL, "sourceKind" text NOT NULL, "sourceId" text NOT NULL, "name" text NOT NULL, "sourceIdentity" text NOT NULL, "serverId" text, "uid" integer NOT NULL DEFAULT (1000), "desiredState" text NOT NULL DEFAULT ('active'), "generation" integer NOT NULL DEFAULT (1), "lastTaskId" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_data_directory_server" FOREIGN KEY ("serverId") REFERENCES "servers" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_data_directory_local_physical" ON "data_directories" ("serverId", "sourceId", "name") WHERE "sourceKind" = 'local'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_data_directory_remote_physical" ON "data_directories" ("sourceId", "name") WHERE "sourceKind" = 'remote'`);
        await queryRunner.query(`CREATE INDEX "IDX_45f0aef27e3a2d1b12d7a17a1a" ON "data_directories" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f891a7fb7e2489c0aef67d630" ON "data_directories" ("sourceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef4992134d9f5b8c7296ccfe4c" ON "data_directories" ("serverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a737ab5c1b4d353af09850bed" ON "data_directories" ("desiredState") `);
        await queryRunner.query(`CREATE TABLE "containers" ("id" text PRIMARY KEY NOT NULL, "server_id" text NOT NULL, "owner_id" text NOT NULL, "name" text NOT NULL, "image_id" text NOT NULL, "created_by" text NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_container_server" FOREIGN KEY ("server_id") REFERENCES "servers" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION, CONSTRAINT "FK_container_image" FOREIGN KEY ("image_id") REFERENCES "images" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_containers_owner_server_name" ON "containers" ("owner_id", "server_id", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e3de1dd71aff12e9ae3d7b7a9" ON "containers" ("server_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b09ee0f2c00ce4b2fc95d0e2b4" ON "containers" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3167e70217fbe27dcf0f93164e" ON "containers" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_5810362a405b6928d7446f8c90" ON "containers" ("created_by") `);
        await queryRunner.query(`CREATE TABLE "network_address_claims" ("id" text PRIMARY KEY NOT NULL, "address" text NOT NULL, "network_key" text NOT NULL, "owner_kind" text NOT NULL, "owner_id" text NOT NULL, "server_id" text, "state" text NOT NULL DEFAULT ('active'), "cleanup_payload_json" text, "reusable_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_network_address_claim_owner" UNIQUE ("owner_kind", "owner_id", "server_id", "address"), CONSTRAINT "CHK_network_address_claim_owner_shape" CHECK (("owner_kind" IN ('container', 'runtime_cleanup') AND "server_id" IS NOT NULL) OR ("owner_kind" IN ('gateway', 'host') AND "server_id" IS NULL)), CONSTRAINT "CHK_network_address_claim_state_shape" CHECK (("state" = 'active' AND "reusable_at" IS NULL) OR ("state" = 'releasing' AND "reusable_at" IS NOT NULL)), CONSTRAINT "CHK_network_address_claim_cleanup_evidence" CHECK (("owner_kind" = 'runtime_cleanup' AND "cleanup_payload_json" IS NOT NULL) OR ("owner_kind" <> 'runtime_cleanup' AND "cleanup_payload_json" IS NULL)), CONSTRAINT "FK_network_address_claim_server" FOREIGN KEY ("server_id") REFERENCES "servers" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE INDEX "IDX_network_address_claim_address" ON "network_address_claims" ("address") `);
        await queryRunner.query(`CREATE INDEX "IDX_network_address_claim_network" ON "network_address_claims" ("network_key") `);
        await queryRunner.query(`CREATE INDEX "IDX_network_address_claim_owner_kind" ON "network_address_claims" ("owner_kind") `);
        await queryRunner.query(`CREATE INDEX "IDX_network_address_claim_owner_id" ON "network_address_claims" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_network_address_claim_server" ON "network_address_claims" ("server_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_network_address_claim_reusable" ON "network_address_claims" ("reusable_at") `);
        await queryRunner.query(`CREATE TABLE "container_mounts" ("id" text PRIMARY KEY NOT NULL, "serverId" text NOT NULL, "containerId" text NOT NULL, "containerName" text NOT NULL, "sourceKind" text NOT NULL, "sourceId" text NOT NULL, "sourceIdentity" text NOT NULL, "userId" text NOT NULL, "dirName" text NOT NULL, "containerPath" text NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_bd6f2763b627a7277559ff1cd08" UNIQUE ("serverId", "containerId", "sourceKind", "sourceId", "userId", "dirName"), CONSTRAINT "UQ_598082ae123d352608cc7ae860e" UNIQUE ("serverId", "containerId", "containerPath"), CONSTRAINT "FK_container_mount_server" FOREIGN KEY ("serverId") REFERENCES "servers" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION, CONSTRAINT "FK_container_mount_container" FOREIGN KEY ("containerId") REFERENCES "containers" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE INDEX "IDX_a6919ad7e67ec037a9bb5813fa" ON "container_mounts" ("serverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb56ee2b38a1bb1e77ce134b4a" ON "container_mounts" ("containerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b13234cfa09f05c207accc3ce4" ON "container_mounts" ("containerName") `);
        await queryRunner.query(`CREATE TABLE "container_desired_specs" ("id" text PRIMARY KEY NOT NULL, "container_id" text NOT NULL, "generation" integer NOT NULL DEFAULT (1), "image_ref" text NOT NULL, "image_default_uid" integer NOT NULL DEFAULT (0), "image_runtime_overrides" text NOT NULL DEFAULT ('{"uid":0,"entrypoint":null,"cmd":null,"init":false}'), "cpu_millis" integer NOT NULL DEFAULT (0), "mem_bytes" text NOT NULL DEFAULT ('0'), "disk_bytes" text NOT NULL DEFAULT ('0'), "gpu_mode" text NOT NULL DEFAULT ('none'), "gpu_indices" text NOT NULL DEFAULT ('[]'), "mounts_json" text NOT NULL DEFAULT ('[]'), "power_intent" text NOT NULL DEFAULT ('running'), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_6b5840483a4ce9c096572c3a0fd" UNIQUE ("container_id"), CONSTRAINT "FK_container_desired_container" FOREIGN KEY ("container_id") REFERENCES "containers" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE INDEX "IDX_6b5840483a4ce9c096572c3a0f" ON "container_desired_specs" ("container_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c7f9806139b7933a0dd07078a5" ON "container_desired_specs" ("power_intent") `);
        await queryRunner.query(`CREATE TABLE "container_lifecycle" ("container_id" text PRIMARY KEY NOT NULL, "phase" text NOT NULL DEFAULT ('provisioning'), "bound_runtime_id" text, "quota_paths_json" text NOT NULL DEFAULT ('[]'), "runtime_spec_hash" text, "active_task_id" text, "last_transition_at" datetime NOT NULL, "failure_reason" text, "failure_code" text, CONSTRAINT "FK_container_lifecycle_container" FOREIGN KEY ("container_id") REFERENCES "containers" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE INDEX "IDX_3b7043e320fb4b65f36fd0e9d6" ON "container_lifecycle" ("phase") `);
        await queryRunner.query(`CREATE INDEX "IDX_b307b9336b0d18eec82b27efda" ON "container_lifecycle" ("bound_runtime_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f5d94248abbb8fcf590a71ae82" ON "container_lifecycle" ("active_task_id") `);
        await queryRunner.query(`CREATE TABLE "gpu_allocations" ("container_id" text PRIMARY KEY NOT NULL, "server_id" text NOT NULL, "gpu_indices_json" text NOT NULL DEFAULT ('[]'), "allocated_at" datetime NOT NULL, CONSTRAINT "FK_gpu_allocation_container" FOREIGN KEY ("container_id") REFERENCES "containers" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_gpu_allocation_server" FOREIGN KEY ("server_id") REFERENCES "servers" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE INDEX "IDX_dd5a44c3d318bffbfcb14bec0a" ON "gpu_allocations" ("server_id") `);
        await queryRunner.query(`CREATE TABLE "agent_tasks" ("id" text PRIMARY KEY NOT NULL, "kind" text NOT NULL, "server_id" text NOT NULL, "resource_type" text NOT NULL, "resource_id" text NOT NULL, "requested_by" text, "request_json" text, "payload_json" text NOT NULL, "payload_hash" text NOT NULL, "admission_class" text NOT NULL DEFAULT ('normal'), "status" text NOT NULL DEFAULT ('pending'), "failure_stage" text, "agent_result_json" text, "dispatch_attempt_count" integer NOT NULL DEFAULT (0), "incomplete_result_count" integer NOT NULL DEFAULT (0), "retry_window_started_at" datetime, "next_dispatch_at" datetime, "finalizer_attempt_count" integer NOT NULL DEFAULT (0), "finalizer_retry_at" datetime, "result_json" text, "error_json" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "started_at" datetime, "last_sent_at" datetime, "completed_at" datetime, CONSTRAINT "FK_agent_tasks_server" FOREIGN KEY ("server_id") REFERENCES "servers" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE INDEX "IDX_856205212c63b8e85fb6b1f74c" ON "agent_tasks" ("kind") `);
        await queryRunner.query(`CREATE INDEX "IDX_de9605b5426c4770a514840bf4" ON "agent_tasks" ("server_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_03e984a85b1589dccf9804bdc4" ON "agent_tasks" ("resource_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_d554bcbd85b5032aeb920966be" ON "agent_tasks" ("resource_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_05e1442acfc89ab1c42bbb347b" ON "agent_tasks" ("requested_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_d4a8c1329ffcda2fd53bae04ad" ON "agent_tasks" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_agent_tasks_finalizer_retry_at" ON "agent_tasks" ("finalizer_retry_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_agent_tasks_next_dispatch_at" ON "agent_tasks" ("next_dispatch_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_agent_tasks_retry_window_started_at" ON "agent_tasks" ("retry_window_started_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_agent_tasks_admission_class" ON "agent_tasks" ("admission_class") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec2db8f08cd7b9d09482fbccf4" ON "agent_tasks" ("last_sent_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_7424655e5f1ac7b86efe650adb" ON "agent_tasks" ("completed_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_b48c3bb93135628c1697489103" ON "agent_tasks" ("resource_type", "resource_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_723bddd80282f71363e53b8fc8" ON "agent_tasks" ("server_id", "status", "last_sent_at") `);
        await queryRunner.query(`CREATE TABLE "resource_locks" ("resource_key" text PRIMARY KEY NOT NULL, "task_id" text NOT NULL, "server_id" text NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_resource_locks_task" FOREIGN KEY ("task_id") REFERENCES "agent_tasks" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION, CONSTRAINT "FK_resource_locks_server" FOREIGN KEY ("server_id") REFERENCES "servers" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE INDEX "IDX_b9702db7db9388c5ac87e4dba8" ON "resource_locks" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3a58f4aa85a2d20e71a0216fff" ON "resource_locks" ("server_id") `);
        await queryRunner.query(`CREATE TABLE "quota_desired" ("id" text PRIMARY KEY NOT NULL, "serverId" text NOT NULL, "userId" text NOT NULL, "numericUserId" integer, "limitBytes" text NOT NULL DEFAULT ('0'), "source" text NOT NULL DEFAULT ('grant'), "generation" integer NOT NULL DEFAULT (1), "lastTaskId" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_c2c0b41c386fe0b37e744b0d14a" UNIQUE ("serverId", "userId"), CONSTRAINT "FK_quota_desired_server" FOREIGN KEY ("serverId") REFERENCES "servers" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE INDEX "IDX_c3daf85543f4ef04423c3b6b70" ON "quota_desired" ("serverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4dae320ee6b54456cc67a6a5fb" ON "quota_desired" ("userId") `);
        await queryRunner.query(`CREATE TABLE "container_ssh_routes" ("container_id" text PRIMARY KEY NOT NULL, "server_id" text NOT NULL, "runtime_id" text NOT NULL, "macvlan_ip" text, "runtime_status" text NOT NULL, "ssh_status" text NOT NULL, "applied_internal_key_generation" integer, "container_host_key_fingerprint" text, "last_error" text, "observed_at" datetime NOT NULL, CONSTRAINT "FK_container_ssh_route_container" FOREIGN KEY ("container_id") REFERENCES "containers" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_container_ssh_route_server" FOREIGN KEY ("server_id") REFERENCES "servers" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE INDEX "IDX_0146629a3d2716c5ce57f10959" ON "container_ssh_routes" ("server_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d420cb66f3506acf88f98901e" ON "container_ssh_routes" ("observed_at") `);
        await queryRunner.query(`CREATE TABLE "http_domain_pools" ("id" text PRIMARY KEY NOT NULL, "wildcard_domain" text NOT NULL, "enabled" boolean NOT NULL DEFAULT (1), "https_enabled" boolean NOT NULL DEFAULT (0), "certificate_pem" text, "encrypted_private_key_pem" text, "certificate_fingerprint" text, "certificate_not_after" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cb7e328837f9129ddd7c7faf73" ON "http_domain_pools" ("wildcard_domain") `);
        await queryRunner.query(`CREATE TABLE "http_proxy_bindings" ("id" text PRIMARY KEY NOT NULL, "hostname" text NOT NULL, "domain_pool_id" text NOT NULL, "owner_id" text NOT NULL, "container_id" text NOT NULL, "target_port" integer NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_http_proxy_binding_pool" FOREIGN KEY ("domain_pool_id") REFERENCES "http_domain_pools" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION, CONSTRAINT "FK_http_proxy_binding_container" FOREIGN KEY ("container_id") REFERENCES "containers" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ca5eecc5ef4869dba298fd57ff" ON "http_proxy_bindings" ("hostname") `);
        await queryRunner.query(`CREATE INDEX "IDX_b6e7fee1c9dc51aaa641d4dcf1" ON "http_proxy_bindings" ("domain_pool_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3097ff91ac5da4cee1ec59f07f" ON "http_proxy_bindings" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ee69092bde95a16c5abd0eeebe" ON "http_proxy_bindings" ("container_id") `);
        await queryRunner.query(`CREATE TABLE "http_hostname_reservations" ("hostname" text PRIMARY KEY NOT NULL, "owner_id" text NOT NULL, "binding_id" text, "state" text NOT NULL DEFAULT ('active'), "reusable_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_http_hostname_reservation_owner" ON "http_hostname_reservations" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_http_hostname_reservation_binding" ON "http_hostname_reservations" ("binding_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_http_hostname_reservation_reusable" ON "http_hostname_reservations" ("reusable_at") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_http_hostname_reservation_reusable"`);
        await queryRunner.query(`DROP INDEX "IDX_http_hostname_reservation_binding"`);
        await queryRunner.query(`DROP INDEX "IDX_http_hostname_reservation_owner"`);
        await queryRunner.query(`DROP TABLE "http_hostname_reservations"`);
        await queryRunner.query(`DROP INDEX "IDX_ee69092bde95a16c5abd0eeebe"`);
        await queryRunner.query(`DROP INDEX "IDX_3097ff91ac5da4cee1ec59f07f"`);
        await queryRunner.query(`DROP INDEX "IDX_b6e7fee1c9dc51aaa641d4dcf1"`);
        await queryRunner.query(`DROP INDEX "IDX_ca5eecc5ef4869dba298fd57ff"`);
        await queryRunner.query(`DROP TABLE "http_proxy_bindings"`);
        await queryRunner.query(`DROP INDEX "IDX_cb7e328837f9129ddd7c7faf73"`);
        await queryRunner.query(`DROP TABLE "http_domain_pools"`);
        await queryRunner.query(`DROP INDEX "IDX_0d420cb66f3506acf88f98901e"`);
        await queryRunner.query(`DROP INDEX "IDX_0146629a3d2716c5ce57f10959"`);
        await queryRunner.query(`DROP TABLE "container_ssh_routes"`);
        await queryRunner.query(`DROP INDEX "IDX_4dae320ee6b54456cc67a6a5fb"`);
        await queryRunner.query(`DROP INDEX "IDX_c3daf85543f4ef04423c3b6b70"`);
        await queryRunner.query(`DROP TABLE "quota_desired"`);
        await queryRunner.query(`DROP INDEX "IDX_3a58f4aa85a2d20e71a0216fff"`);
        await queryRunner.query(`DROP INDEX "IDX_b9702db7db9388c5ac87e4dba8"`);
        await queryRunner.query(`DROP TABLE "resource_locks"`);
        await queryRunner.query(`DROP INDEX "IDX_723bddd80282f71363e53b8fc8"`);
        await queryRunner.query(`DROP INDEX "IDX_b48c3bb93135628c1697489103"`);
        await queryRunner.query(`DROP INDEX "IDX_7424655e5f1ac7b86efe650adb"`);
        await queryRunner.query(`DROP INDEX "IDX_ec2db8f08cd7b9d09482fbccf4"`);
        await queryRunner.query(`DROP INDEX "IDX_d4a8c1329ffcda2fd53bae04ad"`);
        await queryRunner.query(`DROP INDEX "IDX_05e1442acfc89ab1c42bbb347b"`);
        await queryRunner.query(`DROP INDEX "IDX_d554bcbd85b5032aeb920966be"`);
        await queryRunner.query(`DROP INDEX "IDX_03e984a85b1589dccf9804bdc4"`);
        await queryRunner.query(`DROP INDEX "IDX_de9605b5426c4770a514840bf4"`);
        await queryRunner.query(`DROP INDEX "IDX_856205212c63b8e85fb6b1f74c"`);
        await queryRunner.query(`DROP TABLE "agent_tasks"`);
        await queryRunner.query(`DROP INDEX "IDX_de9e42c8e84bd788fe7338fac6"`);
        await queryRunner.query(`DROP INDEX "IDX_5cb449f6fe03a112a3ee38a328"`);
        await queryRunner.query(`DROP INDEX "IDX_9a1c84560aea586f2b405e5b7d"`);
        await queryRunner.query(`DROP INDEX "IDX_51fdeb6bae4a3424f330e19f16"`);
        await queryRunner.query(`DROP INDEX "IDX_dd5a44c3d318bffbfcb14bec0a"`);
        await queryRunner.query(`DROP TABLE "gpu_allocations"`);
        await queryRunner.query(`DROP INDEX "IDX_f5d94248abbb8fcf590a71ae82"`);
        await queryRunner.query(`DROP INDEX "IDX_b307b9336b0d18eec82b27efda"`);
        await queryRunner.query(`DROP INDEX "IDX_3b7043e320fb4b65f36fd0e9d6"`);
        await queryRunner.query(`DROP TABLE "container_lifecycle"`);
        await queryRunner.query(`DROP INDEX "IDX_c7f9806139b7933a0dd07078a5"`);
        await queryRunner.query(`DROP INDEX "IDX_6b5840483a4ce9c096572c3a0f"`);
        await queryRunner.query(`DROP TABLE "container_desired_specs"`);
        await queryRunner.query(`DROP INDEX "IDX_b13234cfa09f05c207accc3ce4"`);
        await queryRunner.query(`DROP INDEX "IDX_bb56ee2b38a1bb1e77ce134b4a"`);
        await queryRunner.query(`DROP INDEX "IDX_a6919ad7e67ec037a9bb5813fa"`);
        await queryRunner.query(`DROP TABLE "container_mounts"`);
        await queryRunner.query(`DROP INDEX "IDX_5810362a405b6928d7446f8c90"`);
        await queryRunner.query(`DROP INDEX "IDX_3167e70217fbe27dcf0f93164e"`);
        await queryRunner.query(`DROP INDEX "IDX_b09ee0f2c00ce4b2fc95d0e2b4"`);
        await queryRunner.query(`DROP INDEX "IDX_3e3de1dd71aff12e9ae3d7b7a9"`);
        await queryRunner.query(`DROP INDEX "UQ_containers_owner_server_name"`);
        await queryRunner.query(`DROP INDEX "IDX_network_address_claim_reusable"`);
        await queryRunner.query(`DROP INDEX "IDX_network_address_claim_server"`);
        await queryRunner.query(`DROP INDEX "IDX_network_address_claim_owner_id"`);
        await queryRunner.query(`DROP INDEX "IDX_network_address_claim_owner_kind"`);
        await queryRunner.query(`DROP INDEX "IDX_network_address_claim_network"`);
        await queryRunner.query(`DROP INDEX "IDX_network_address_claim_address"`);
        await queryRunner.query(`DROP TABLE "network_address_claims"`);
        await queryRunner.query(`DROP TABLE "containers"`);
        await queryRunner.query(`DROP INDEX "IDX_4a737ab5c1b4d353af09850bed"`);
        await queryRunner.query(`DROP INDEX "IDX_ef4992134d9f5b8c7296ccfe4c"`);
        await queryRunner.query(`DROP INDEX "IDX_9f891a7fb7e2489c0aef67d630"`);
        await queryRunner.query(`DROP INDEX "IDX_45f0aef27e3a2d1b12d7a17a1a"`);
        await queryRunner.query(`DROP INDEX "IDX_data_directory_remote_physical"`);
        await queryRunner.query(`DROP INDEX "IDX_data_directory_local_physical"`);
        await queryRunner.query(`DROP TABLE "data_directories"`);
        await queryRunner.query(`DROP INDEX "IDX_102ce17e2ec3bf21db37f9338a"`);
        await queryRunner.query(`DROP INDEX "IDX_0fadae89939ccf83ae0d4bc69d"`);
        await queryRunner.query(`DROP INDEX "IDX_a7881dfbbf08a86770d6452c83"`);
        await queryRunner.query(`DROP TABLE "remote_fs_server_assignments"`);
        await queryRunner.query(`DROP INDEX "IDX_8c780d804567b09ff28869b5cc"`);
        await queryRunner.query(`DROP INDEX "IDX_2c825d1696c548aae334d5e1b5"`);
        await queryRunner.query(`DROP INDEX "IDX_4c8b9d866b47f9b769192471b4"`);
        await queryRunner.query(`DROP TABLE "mount_source_grants"`);
        await queryRunner.query(`DROP INDEX "IDX_e419b091a9c1a5aa47aad3e372"`);
        await queryRunner.query(`DROP INDEX "IDX_remote_fs_mount_host_path"`);
        await queryRunner.query(`DROP TABLE "remote_fs_mounts"`);
        await queryRunner.query(`DROP INDEX "IDX_1060e7b773af9bb188a604f9b1"`);
        await queryRunner.query(`DROP INDEX "IDX_d401dd45fe95076e33a4c8b796"`);
        await queryRunner.query(`DROP INDEX "IDX_b620a683f3df3f8b2a5eaf13af"`);
        await queryRunner.query(`DROP INDEX "IDX_b8191e1eefdba566bcbc1dc88f"`);
        await queryRunner.query(`DROP TABLE "image_grants"`);
        await queryRunner.query(`DROP INDEX "IDX_87ac83586ca63f150559d7809a"`);
        await queryRunner.query(`DROP INDEX "IDX_07fac52f8b667d912da6065f64"`);
        await queryRunner.query(`DROP INDEX "IDX_4bbc526cc1fc7905565eb41ca3"`);
        await queryRunner.query(`DROP TABLE "server_grants"`);
        await queryRunner.query(`DROP INDEX "IDX_fdef099303bcf0ffd9a4a7b18f"`);
        await queryRunner.query(`DROP INDEX "IDX_1aa8d31831c3126947e7a713c2"`);
        await queryRunner.query(`DROP TABLE "group_members"`);
        await queryRunner.query(`DROP TABLE "groups"`);
        await queryRunner.query(`DROP INDEX "IDX_cee229609cb2b7c62a2fc3a974"`);
        await queryRunner.query(`DROP INDEX "IDX_2dc33f7f3c22e2e7badafca1d1"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "images"`);
        await queryRunner.query(`DROP INDEX "IDX_servers_host_fingerprint"`);
        await queryRunner.query(`DROP INDEX "IDX_servers_quarantine_code"`);
        await queryRunner.query(`DROP INDEX "IDX_3f639177f557bf7d508db5fa63"`);
        await queryRunner.query(`DROP INDEX "IDX_5c148a3e0a635fa398f28a1cc2"`);
        await queryRunner.query(`DROP TABLE "servers"`);
        await queryRunner.query(`DROP TABLE "ssh_proxy_host_keys"`);
        await queryRunner.query(`DROP INDEX "IDX_39773aacbb3afac30ff3d62c4b"`);
        await queryRunner.query(`DROP TABLE "user_internal_ssh_keys"`);
        await queryRunner.query(`DROP INDEX "IDX_e0ddc8263f98e68528814ac369"`);
        await queryRunner.query(`DROP TABLE "ssh_public_keys"`);
        await queryRunner.query(`DROP INDEX "IDX_2a2ce819bd75cc0193bfb2692b"`);
        await queryRunner.query(`DROP TABLE "api_tokens"`);
        await queryRunner.query(`DROP INDEX "IDX_610102b60fea1455310ccd299d"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
