#!/usr/bin/env bash

set -euo pipefail

POC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$POC_DIR/../../.." && pwd)"
RUN_LABEL_KEY="io.nyabase.e2e.run"
POC_LABEL_KEY="io.nyabase.e2e.poc"

poc_init() {
  RUN_ID="${NYABASE_FULL_PROXY_POC_RUN_ID:-full-proxy-poc-$(date -u +%Y%m%dT%H%M%SZ)-$$}"
  if [[ ! "$RUN_ID" =~ ^[a-z0-9][a-z0-9_.-]{2,80}$ ]]; then
    echo "invalid Full proxy PoC run id: $RUN_ID" >&2
    return 2
  fi
  ARTIFACT_DIR="${NYABASE_FULL_PROXY_POC_ARTIFACT_DIR:-$REPO_ROOT/e2e/.runtime/$RUN_ID/full-proxies}"
  if [[ "$ARTIFACT_DIR" != /* ]]; then
    echo "artifact directory must be absolute" >&2
    return 2
  fi
  PRIVATE_DIR="$ARTIFACT_DIR/private"
  STATE_FILE="$ARTIFACT_DIR/state.env"
  LOG_DIR="$ARTIFACT_DIR/logs"
  mkdir -p "$ARTIFACT_DIR" "$LOG_DIR"
  export RUN_ID ARTIFACT_DIR PRIVATE_DIR STATE_FILE LOG_DIR POC_DIR REPO_ROOT
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "required command is missing: $1" >&2
    return 1
  }
}

state_put() {
  printf '%s=%q\n' "$1" "$2" >>"$STATE_FILE"
}

load_state() {
  if [[ ! -f "$STATE_FILE" ]]; then
    echo "Full proxy PoC state is missing: $STATE_FILE" >&2
    return 1
  fi
  # The state file is generated by state_put with shell-escaped values.
  # shellcheck disable=SC1090
  source "$STATE_FILE"
  export RUN_ID ARTIFACT_DIR PRIVATE_DIR STATE_FILE LOG_DIR
}

control_request() {
  local method="$1"
  local path="$2"
  curl --silent --show-error --fail \
    --request "$method" \
    --cacert "$PRIVATE_DIR/ca.crt" \
    --resolve "control:${CONTROL_PORT}:127.0.0.1" \
    --header "X-Poc-Admin: $(<"$PRIVATE_DIR/admin-token")" \
    "https://control:${CONTROL_PORT}${path}"
}

wait_for_control_state() {
  local mode="$1"
  local output="$2"
  local attempt
  for attempt in $(seq 1 120); do
    if control_request GET /admin/state >"$output" 2>/dev/null \
      && node "$POC_DIR/state-check.mjs" "$mode" <"$output"; then
      return 0
    fi
    sleep 0.25
  done
  echo "control state did not reach $mode" >&2
  return 1
}

collect_logs() {
  mkdir -p "$LOG_DIR"
  local container name
  while IFS= read -r container; do
    [[ -n "$container" ]] || continue
    name="$(docker inspect --format '{{.Name}}' "$container" 2>/dev/null | sed 's#^/##')"
    [[ -n "$name" ]] || name="$container"
    docker logs "$container" >"$LOG_DIR/${name}.log" 2>&1 || true
  done < <(docker ps -aq --filter "label=${RUN_LABEL_KEY}=${RUN_ID}")
}
